### PR TITLE
kernel: Enable socket monitoring interface

### PR DESCRIPTION
**Pull request by lategoodbye**
In order to debug network related issues enable the socket monitoring interface used by userspace tools like ss. This tool is included in iproute2.

There is no noticable increase of kernel image size.

### CODE REVIEW

**Review by mhei — APPROVED** [review]
Fine with me

**Comment by mooraby** [comment]
I will run a quick build with Yocto and let you know

**Comment by lategoodbye** [comment]
Test scenario:

1. Install latest developer image
2. Connect to Charge Control C via ssh
3. run `ss -tenmoi` on the Charge Control C

Expected similiar output (skmem part is necessary):
```
State Recv-Q Send-Q           Local Address:Port             Peer Address:Port  Process                                                                         
ESTAB 0      0        [::ffff:192.168.1.12]:22     [::ffff:192.168.1.129]:56256  timer:(keepalive,119min,0) ino:62663 sk:2 cgroup:/system.slice/sshd.socket <->
	 skmem:(r0,rb131072,t0,tb44800,f0,w0,o0,bl0,d0) ts sack cubic wscale:7,6 rto:210 rtt:8.607/12.392 ato:40 mss:1448 pmtu:1500 rcvmss:1448 advmss:1448 cwnd:10 bytes_sent:2885 bytes_acked:2885 bytes_received:3353 segs_out:26 segs_in:30 data_segs_out:16 data_segs_in:16 send 13458813bps lastsnd:10 lastrcv:10 lastack:10 pacing_rate 26916056bps delivery_rate 9685616bps delivered:17 app_limited busy:180ms rcv_space:14600 rcv_ssthresh:64076 minrtt:0.826
```

**Review by mooraby — APPROVED** [review]
works.. Just ran the recipe and made sure that required kernal configs are built

**Comment by lategoodbye** [comment]
Thanks

**Pull request merged**
